invoice = float(input('Type an amount of invoice: '))
# print (invoice)
vat = (invoice * 0.12)
total_amount = float(vat + invoice)
print ('The total amount after the adition of vat percentage of the number you put is', total_amount) 
